### ISSUE TITLE
gitlab registry doesn't have latest tag

### ISSUE THREAD

**Issue by legoktm** [anarcat/debian-airsonic#3]
```
$ docker --debug pull registry.gitlab.com/anarcat/debian-airsonic
Using default tag: latest
Error response from daemon: manifest for registry.gitlab.com/anarcat/debian-airsonic:latest not found: manifest unknown: manifest unknown
```

I peeked at the gitlab CI, and it appears to be pushing the image as `registry.gitlab.com/anarcat/debian-airsonic:master` rather than a `latest` tag that docker defaults to.

```
$ docker pull registry.gitlab.com/anarcat/debian-airsonic:master
master: Pulling from anarcat/debian-airsonic
7e2b2a5af8f6: Pull complete 
17360a1631ce: Pull complete 
4af080a8d04a: Pull complete 
f8d2f367de9d: Pull complete 
Digest: sha256:2201f93f689c006595cbbb34057eb38156b76354dbd177791d0b364dfda6282a
Status: Downloaded newer image for registry.gitlab.com/anarcat/debian-airsonic:master
registry.gitlab.com/anarcat/debian-airsonic:master
```

Could the CI be updated to also push a latest tag (preferred IMO) or update the README to indicate that the master tag needs to be pulled? Thanks :)

**Comment by anarcat** [comment]
forgot to tag this issue, but i think 576cad2 should fix this problem...

**Comment by anarcat** [comment]
hum, well it seems gitlab mirroring is lying to me:

>  This project is mirrored from https://github.com/anarcat/debian-airsonic.git. Pull mirroring updated 2 minutes ago. 

... yet the commits here do not show up there.

*shrug*, i guess they will end up there eventually. i'll build and push 10.6.2 to docker now at least.

**Comment by anarcat** [comment]
weird. the CI got ran, and git pull on gitlab shows the commits, but the web UI doesn't, at least not in:

https://gitlab.com/anarcat/debian-airsonic/-/commits/master

... and in the main page. go figure.

in any case, `docker pull` works now, so we're good:

```
$ docker pull registry.gitlab.com/anarcat/debian-airsonic
Using default tag: latest
latest: Pulling from anarcat/debian-airsonic
90fe46dd8199: Downloading [==========================>                        ]  26.92MB/50.38MB
bcdd5df15040: Downloading [======>                                            ]     27MB/193.3MB
c1b21d5ada19: Download complete 
caa1e8587434: Downloading [=================>                                 ]  26.46MB/77.58MB
```

interestingly, it's a different image than the one build locally, so i guess it's not reproducible out of the box...

**Comment by legoktm** [comment]
Bizarre behavior on the gitlab side, but thanks for taking care of this :)
